INSERT INTO backgrounds (name,origin_id,sourcebook_id) VALUES
('Initiate','1','1'),
('Scribe','1','1'),
('Mercenary','2','1'),
('Raider','2','1'),
('Settler','2','1'),
('Trader','2','1'),
('Wanderer','2','1'),
('Brute','3','1'),
('Skirmisher','3','1'),
('Miss nanny','4','1'),
('Mister farmhand','4','1'),
('Mister gutsy','4','1'),
('Mister handy','4','1'),
('Nurse handy','4','1'),
('Mercenary','5','1'),
('Raider','5','1'),
('Settler','5','1'),
('Trader','5','1'),
('Wanderer','5','1'),
('Resident','6','1'),
('Security','6','1'),
('Rifleman','7','3'),
('Tough','7','3'),
('Trooper','8','3'),
('Marksman','8','3'),
('Crimson caravaneer','8','3'),
('Protectron','9','3'),
('Fire brigadier','9','3'),
('Medic','9','3'),
('Utility','9','3'),
('Nukatron','9','3'),
('Protectron x','9','3'),
('Servomech','10','3'),
('Us army model','10','3'),
('Errant personality','10','3'),
('Standard','11','3'),
('Infiltrator','12','3'),
('Seeker','12','3'),
('Missionary','13','4'),
('Zealot','13','4'),
('Us military model','14','4'),
('Devil','14','4'),
('Caravan guard','14','4'),
('Ex-knight','15','4'),
('Ex-scribe','15','4'),
('Nightkin','16','4'),
('Modernist','17','4'),
('Ritualist','17','4'),
('Naturalist','17','4');