INSERT INTO weapon_mods (name,prefix,slot,wgt,cost) VALUES
('Hardened','Hardened','1','0','20'),
('Powerful','Powerful','1','1','25'),
('Advanced','Advanced','1','2','35'),
('Calibrated','Calibrated','1','0','25'),
('Automatic','Auto','1','1','30'),
('Hair Trigger','Hair Trigger','1','0','20'),
('.38 Receiver','.38','1','3','20'),
('.308 Receiver','.308','1','4','40'),
('.45 Receiver','.45','1','2','19'),
('.50 Receiver','.50','1','4','30'),
('Automatic Piston','Automatic','1','2','75'),
('12.7mm Receiver','12.7mm','1','3','50'),
('.357 Receiver','.357','1','0','20'),
('.45-70 Receiver','.45-70','1','4','40'),
('Snubnose','Snub-nosed','2','-1','0'),
('Bull','Bull Barreled','2','0','10'),
('Long (Small Guns)','Long','2','1','20'),
('Long (Energy Weapons)','Long','2','2','20'),
('Long (Flamer)','Long','2','2','28'),
('Long (Junk Jet)','Long','2','2','20'),
('Ported','Ported','2','1','35'),
('Vented','Vented','2','1','36'),
('Sawed-Off','Sawed-off','2','-2','3'),
('Shielded','Shielded','2','0','37'),
('Finned','Finned','2','2','15'),
('Bracketed Short','-','2','0','6'),
('Splitter','Scattergun','2','1','31'),
('Automatic','Automatic','2','1','24'),
('Bracketed Long','-','2','2','25'),
('Improved','Improved','2','1','26'),
('Sniper','Sniper','2','2','30'),
('Flamer','Thrower','2','1','35'),
('Charging','Charging','2','10','357'),
('Accelerated','High-Speed','2','5','45'),
('Tri-Barrel (Minigun)','High-Powered','2','3','75'),
('Triple','Triple Barrel','2','16','143'),
('Quad','Quad Barrel','2','20','218'),
('Large','High Capacity','5','1','-3'),
('Quick-Eject','Quick','5','0','8'),
('Large Quick-Eject','Quick High Capacity','5','1','23'),
('Comfort (Small Guns)','Comfort','4','0','6'),
('Sharpshooter’s','Sharpshooter’s','4','0','10'),
('Full (Small Guns)','-','3','1','10'),
('Full (Energy Weapons)','-','3','1','15'),
('Marksman’s','Marksman’s','3','2','20'),
('Recoil Compensating (Small Guns, Energy Weapons)','Recoil Compensated','3','2','3'),
('Recoil Compensating (Junk Jet, Cryolator)','Recoil Compensated','3','2','40'),
('Standard','-','3','1','10'),
('Reflex (Small Guns, Energy Weapons, Cryolator)','Tactical','6','0','14'),
('Reflex (Gatling Laser)','Tactical','6','1','169'),
('Short Scope (Small Guns, Energy Weapons)','Scoped','6','1','11'),
('Long Scope','Scoped','6','1','29'),
('Short Night Vision','Night Vision','6','1','38'),
('Long Night Vision','Night Vision','6','1','50'),
('Recon','Recon','6','1','59'),
('Gunner (Junk Jet)','Tactical','6','1','5'),
('Gunner (Minigun)','Tactical','6','1','68'),
('Scope','Scoped','6','6','143'),
('Night Vision','Night Vision','6','6','248'),
('Targeting Computer','Targeting','6','7','293'),
('Bayonet','Bayoneted','7','2','10'),
('Compensator','Compensated','7','1','15'),
('Muzzle Break','Muzzled','7','1','30'),
('Suppressor','Supressed','7','2','45'),
('Beam Splitter (Energy Weapons)','Scattered','7','1','15'),
('Beam Focuser (Energy Weapons)','Focused','7','1','20'),
('Gyro Compensating Lens','Targeting','7','1','25'),
('Electric Signal Carrer Antennae','Electrified','7','0','30'),
('Signal Repeater','Automatic','7','0','60'),
('Electrification Module','Electrified','7','1','70'),
('Ignition Module','Flaming','7','1','130'),
('Shredder','Bayoneted Shredding','7','5','5'),
('Stabilizer','Muzzled','7','2','60'),
('Full Capacitors','High Capacity','8','0','37'),
('Capacitor Boosting Coil','Max Capacity','8','2','82'),
('Beta Wave Tuner (Energy Weapons)','Incendiary','8','0','30'),
('Beta Wave Tuner (Gatling Laser)','Incendiary','8','1','57'),
('Boosted Capacitor (Energy Weapons)','Boosted','8','0','35'),
('Boosted Capacitor (Gatling Laser)','Boosted','8','1','94'),
('Photon Exciter (Energy Weapons)','Excited','8','0','30'),
('Photon Exciter (Gatling Laser)','Excited','8','1','19'),
('Photon Agitator (Energy Weapons)','Agitated','8','1','35'),
('Photon Agitator (Gatling Laser)','Agitated','8','3','132'),
('Three-Crank','Three-crank','8','0','4'),
('Four-Crank','Four-crank','8','1','8'),
('Five-Crank','Five-crank','8','1','12'),
('Six-Crank','Six-crank','8','2','16'),
('Deep Dish','Long','9','2','72'),
('Napalm','Napalmer','10','7','59'),
('Large (Flamer)','High Capacity','11','3','28'),
('Huge (Flamer)','Max Capacity','11','6','34'),
('Compression','Compressed','12','0','22'),
('Vaporization','Vaporizing','12','0','47'),
('Beam Focuser (Gatling Laser)','Focused','12','0','22'),
('Serrated (Sword)','Serrated','13','0','25'),
('Serrated (Knife)','Serrated','13','0','12'),
('Serrated (Machete)','Serrated','13','0','12'),
('Serrated (Switchblade)','Serrated','13','0','12'),
('Electrified','Electrified','13','0','50'),
('Electrified Serrated','Electrified Serrated','13','0','75'),
('Stun Pack','Stunning','13','0','100'),
('Stealth','Stealth','13','0','18'),
('Curved','Curved','13','1','15'),
('Extended','Extended','13','3','25'),
('Extra Flame Jets','Searing','13','1','100'),
('Extra Claw','Large','13','2','22'),
('Barbed (Bat)','Barbed','14','0','5'),
('Barbed (Pool Cue)','Barbed','14','1','13'),
('Barbed (Cane)','Barbed','14','0','3'),
('Spiked (Bat)','Spiked','14','1','7'),
('Spiked (Board)','Spiked','14','1','6'),
('Spiked (Lead Pipe)','Spiked','14','1','4'),
('Spiked (Rolling Pin, Cane)','Spiked','14','0','3'),
('Spiked (Boxing Glove, Knuckles)','Spiked','14','0','3'),
('Sharp (Bat)','Sharp','14','1','7'),
('Sharp (Pool Cue, Rolling Pin)','Sharp','14','0','3'),
('Sharp (Knuckles)','Sharp','14','0','3'),
('Chain-Wrapped','Chain-wrapped','14','1','10'),
('Bladed (Bat)','Bladed','14','2','12'),
('Bladed (Board)','Bladed','14','2','10'),
('Bladed (Tire Iron)','Bladed','14','1','12'),
('Bladed (Knuckles)','Bladed','14','0','5'),
('Puncturing (Board)','Puncturing','14','1','9'),
('Puncturing (Pipe Wrench)','Puncturing','14','1','13'),
('Puncturing (Sledgehammer)','Puncturing','14','5','18'),
('Puncturing (Boxing Glove, Knuckles)','Puncturing','14','0','4'),
('Puncturing (Power Fist)','Puncturing','14','1','45'),
('Heavy (Lead Pipe)','Heavy','14','2','11'),
('Heavy (Pipe Wrench)','Weighted','14','7','12'),
('Heavy (Sledgehammer)','Heavy','14','9','30'),
('Hooked','Hooked','14','0','9'),
('Extra Heavy','Heavy','14','7','22'),
('Electrified','Shock','14','0','15'),
('Stun Pack (Baton)','Stunning','14','0','30'),
('Stun Pack (Super Sledge)','Stunning','14','0','360'),
('Heating Coil (Super Sledge)','Heated','14','0','180'),
('Heating Coil (Power Fist)','Heated','14','0','100'),
('Lead Lining','Lead-lined','14','1','7'),
('Overcharged','Overcharged','14','0','20'),
('Long (M79, Broadsider)','Long','2','2','40'),
('Caustic','Caustic','10','2','30'),
('Large Ampoule','High Capacity','11','2','22'),
('Large Vial','Max Capacity','11','4','40'),
('Fusion (Alien Blaster)','Converted','5','0','21'),
('Capacitor Mk III','Mk III','8','0','4'),
('Capacitor Mk IV','Mk IV','8','1','8'),
('Capacitor Mk V','Mk V','8','1','12'),
('Capacitor Mk VI','Mk VI','8','2','16'),
('Light','Fluted','2','3','30'),
('Multi Shot Canister','Repeating','1','1','45'),
('M79 Launcher','Converted','1','0','3'),
('Crystallizing','Crystallized','2','5','40'),
('Fusion (Cryolator)','Converted','5','0','21'),
('Barbed Harpoon','Barbed','5','0','21'),
('Flechette Darts','Tiny','5','0','15'),
('Recoil Compensating (Harpoon Gun)','Recoil Compensated','3','15','45'),
('Gunner (Harpoon Gun)','Tactical','6','0','17'),
('Short Scope (Harpoon Gun)','Scoped','6','1','28'),
('Armor Piercing','AP','1','0','3'),
('Armor Piercing Automatic','AP Auto','1','1','40'),
('Hardened Automatic','Hardened Auto','1','2','58'),
('Rapid Automatic','Rapid','1','2','58'),
('Calibrated Powerful','Calibrated Powerful','1','3','68'),
('Powerful Automatic','Powerful Auto','1','4','88'),
('Hardened Piercing Auto','Hardened AP Auto','1','3','78'),
('9mm Receiver','9mm','1','-1','10'),
('Gamma Wave Emitter (Energy Weapons)','Fiery','8','1','14'),
('Gamma Wave Emitter (Gatling Laser)','Fiery','8','3','169'),
('Maximized Capacitor (Energy Weapons)','Maximized','8','1','17'),
('Maximized Capacitor (Gatling Laser)','Maximized','8','3','207'),
('Boosted Photon Agitator (Energy Weapons)','Boosted Agitated','8','1','20'),
('Boosted Photon Agitator (Gatling Gun)','Boosted Agitated','8','5','244'),
('Boosted Gamma Wave Emitter (Energy Weapons)','Boosted Firey','8','1','23'),
('Boosted Gamma Wave Emitter (Gatling Laser)','Boosted Firey','8','5','282'),
('Overcharged Capacitor (Energy Weapons)','Overcharged','8','1','42'),
('Overcharged Capacitor (Gatling Laser)','Overcharged','8','5','319'),
('Improved Long','Improved Long','2','1','15'),
('Improved Automatic','Improved Auto','2','1','18'),
('Improved Sniper','Improved Charging','2','1','21'),
('Improved Splitter','Improved Scattergun','2','1','25'),
('Amplified Beam Splitter','Improved Scattered','7','1','15'),
('Fine-tuned Beam Focuser','Improved Focused','7','1','18'),
('Quantum Gyro-Compensating Lens','Improved Targeting','7','1','21'),
('Heavy','-','2','3','135'),
('Long (Auto Grenade Launcher)','Long','2','2','45'),
('25mm Grenade','25mm','1','3','135'),
('Speedy','-','1','1','35'),
('Long (Gatling Gun)','Long','2','2','158'),
('Comfort (Gatling (Plasma) Gun)','Comfort Grip','4','3','90'),
('Extra-Large Magazine','-','5','2','28'),
('Front Sight Ring','Sighted','6','2','158'),
('Large Bayonet','Bayoneted','7','5','18'),
('Ported (Gatling Plasma)','Ported','2','6','81'),
('Reflex (Gatling Plasma)','Sighted','6','2','50'),
('Beam Splitter (Gatling Plasma)','Scattered','12','3','20'),
('Beam Focuser (Gatling Plasma)','Focused','12','4','41'),
('Tri-Barrel (Gauss Minigun)','Triple Barrel','2','4','91'),
('Penta-Barrel','Penta Barrel','2','12','182'),
('Tesla Coil Capacitor','Tesla Capacitor','8','8','91'),
('Tesla Coil Dynamo','Tesla Dynamo','8','12','136'),
('Calibrated','-','8','3','140'),
('Pulse','Pulse','8','3','70'),
('High Speed Electrode','Rapid','8','3','105'),
('Long (Plasma Caster)','-','2','5','128'),
('Compound','Compound','15','1','30'),
('Iron','-','6','1','10'),
('Glow','Glow-Sighted','6','1','15'),
('Heavy','Heavy','15','1','30'),
('Repeating','Repeating','15','2','75'),
('Multiple Launch','Peppered','15','4','60'),
('Electrified (Assaultron Blade, Auto Axe)','Electrified','13','0','50'),
('Burning','Burning','13','0','50'),
('Poisoned','Toxic','13','0','50'),
('Turbo','Turbo','13','2','50'),
('Dual Bar','Dual','13','1','30'),
('Bow Bar','Bow Bar','13','2','45'),
('Long Bow Bar','Long Bow Bar','13','3','60'),
('Flamer','Flaming','12','2','90'),
('Liquid Nitrogen','Sub-Zero','10','8','80'),
('Compressed Tubing','Calibrated','2','1','28'),
('Wide Diffusion','Spray','12','2','65'),
('Aerosolizer','Vaporizing','12','2','65'),
('Bladed Exhaust','Battle','12','1','65'),
('Secure','Secure','1','0','0'),
('Powered','Powered','1','0','0'),
('Aerodynamic','Aerodynamic','2','0','0'),
('Shocking Coils','Surging','14','0','100'),
('Extended','Extended','2','1','20'),
('Tactical','Tactical','4','0','28'),
('Snap','Double Action','2','0','143'),
('3-Shot Chamber','3-Shot','2','8','218'),
('6-Shot Chamber','6-Shot','2','10','250'),
('Balanced','Balanced','3','10','250');